 -- tabele, constraints, sekwencje/identity, indeksy

 -- 01_schema_oracle.sql
-- Oracle schema for "komis" project

-- Optional cleanup (uncomment if you want re-runs):
-- BEGIN
--   FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
--     'KOMIS','PLAC','SAMOCHOD','DOSTAWA','SPRZEDAWCA','FAKTURA','KLIENT',
--     'KARTOTEKA_TRANSAKCJI','HISTORIA_CEN','UBEZPIECZENIE','AUDIT_LOG'
--   )) LOOP
--     EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS';
--   END LOOP;
-- END;
-- /

--------------------------------------------------------------------------------
CREATE TABLE komis
(
    id_komis      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nip           NUMBER(10) NOT NULL,
    nazwa         VARCHAR2(30) NOT NULL,
    panstwo       VARCHAR2(30) NOT NULL,
    miasto        VARCHAR2(30) NOT NULL,
    ulica         VARCHAR2(30) NOT NULL,
    nr_budynku    NUMBER NOT NULL,
    nr_lokalu     VARCHAR2(10),
    kod_pocztowy  CHAR(6) NOT NULL,
    telefon       VARCHAR2(15),
    e_mail        VARCHAR2(30),
    CONSTRAINT uq_komis_nip UNIQUE (nip)
);

--------------------------------------------------------------------------------
CREATE TABLE plac
(
    id_plac        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kraj           VARCHAR2(30) DEFAULT 'Polska' NOT NULL,
    miejscowosc    VARCHAR2(30) NOT NULL,
    ulica          VARCHAR2(30) NOT NULL,
    nr_dzialki     VARCHAR2(20) NOT NULL,
    id_komis       NUMBER,
    CONSTRAINT fk_komis_plac
        FOREIGN KEY (id_komis)
        REFERENCES komis(id_komis)
        ON DELETE CASCADE
);

--------------------------------------------------------------------------------
CREATE TABLE samochod
(
    id_samochod           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nr_rejestracyjny      VARCHAR2(7),
    nr_vin                CHAR(17) NOT NULL,
    marka                 VARCHAR2(30) NOT NULL,
    model                 VARCHAR2(30) NOT NULL,
    rocznik               NUMBER(4) NOT NULL,
    przebieg              NUMBER(12,2) NOT NULL,
    silnik                NUMBER(4,2) NOT NULL,
    paliwo                VARCHAR2(30) NOT NULL,
    moc                   NUMBER NOT NULL,
    kolor                 VARCHAR2(30) NOT NULL,
    rodzaj_pojazdu        VARCHAR2(30) NOT NULL,
    ladownosc             NUMBER(4,2),
    gotowy_do_sprzedazy   NUMBER(1) NOT NULL,
    cena                  NUMBER(20,2) NOT NULL,
    opis                  CLOB,
    CONSTRAINT ck_samochod_gotowy CHECK (gotowy_do_sprzedazy IN (0,1)),
    CONSTRAINT uq_samochod_nr UNIQUE (nr_rejestracyjny, nr_vin)
);

--------------------------------------------------------------------------------
CREATE TABLE dostawa
(
    id_dostawa          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_dostawy        DATE NOT NULL,
    kraj_pochodzenia    VARCHAR2(50) NOT NULL,
    czy_zarejestrowany  NUMBER(1) NOT NULL,
    czy_uszkodzony      NUMBER(1) NOT NULL,
    id_plac             NUMBER,
    id_samochod         NUMBER,
    CONSTRAINT ck_dostawa_reg CHECK (czy_zarejestrowany IN (0,1)),
    CONSTRAINT ck_dostawa_usz CHECK (czy_uszkodzony IN (0,1)),
    CONSTRAINT fk_samochod_dostawa
        FOREIGN KEY (id_samochod)
        REFERENCES samochod(id_samochod)
        ON DELETE CASCADE,
    CONSTRAINT fk_plac_dostawa
        FOREIGN KEY (id_plac)
        REFERENCES plac(id_plac)
        ON DELETE CASCADE
);

--------------------------------------------------------------------------------
CREATE TABLE sprzedawca
(
    id_sprzedawca  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imie           VARCHAR2(30) NOT NULL,
    nazwisko       VARCHAR2(30) NOT NULL,
    nr_telefonu    VARCHAR2(30),
    e_mail         VARCHAR2(50),
    id_komis       NUMBER,
    id_plac        NUMBER,
    CONSTRAINT fk_komis_sprzedawca
        FOREIGN KEY (id_komis)
        REFERENCES komis(id_komis)
        ON DELETE CASCADE,
    CONSTRAINT fk_plac_sprzedawca
        FOREIGN KEY (id_plac)
        REFERENCES plac(id_plac)
        ON DELETE CASCADE
);

--------------------------------------------------------------------------------
CREATE TABLE faktura
(
    id_faktura      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nr_faktury      VARCHAR2(10) NOT NULL,
    rabat           NUMBER(5),
    sposob_zaplaty  VARCHAR2(30) NOT NULL,
    czy_zaplacono   NUMBER(1) NOT NULL,
    CONSTRAINT ck_faktura_zapl CHECK (czy_zaplacono IN (0,1)),
    CONSTRAINT uq_faktura_nr UNIQUE (nr_faktury)
);

--------------------------------------------------------------------------------
CREATE TABLE klient
(
    id_klient         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imie              VARCHAR2(30) NOT NULL,
    nazwisko          VARCHAR2(30) NOT NULL,
    pesel             CHAR(11) NOT NULL,
    rodzaj_dokumentu  VARCHAR2(50) NOT NULL,
    nr_dokumentu      VARCHAR2(30) NOT NULL,
    panstwo           VARCHAR2(30),
    miasto            VARCHAR2(50),
    ulica             VARCHAR2(50),
    nr_domu           NUMBER,
    nr_mieszkania     VARCHAR2(10),
    kod               VARCHAR2(10),
    telefon           VARCHAR2(30),
    CONSTRAINT uq_klient_pesel UNIQUE (pesel)
);

--------------------------------------------------------------------------------
CREATE TABLE kartoteka_transakcji
(
    id_transakcja           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rodzaj                  VARCHAR2(15) NOT NULL,
    data_transakcji         DATE NOT NULL,
    samochod_w_rozliczeniu  NUMBER(1) NOT NULL,
    uwagi                   CLOB,
    id_samochod             NUMBER,
    id_klient               NUMBER,
    id_sprzedawca           NUMBER,
    id_plac                 NUMBER,
    id_faktura              NUMBER,
    CONSTRAINT ck_trans_rozl CHECK (samochod_w_rozliczeniu IN (0,1)),
    CONSTRAINT fk_samochod_transakcja
        FOREIGN KEY (id_samochod)
        REFERENCES samochod(id_samochod)
        ON DELETE CASCADE,
    CONSTRAINT fk_klient_transakcja
        FOREIGN KEY (id_klient)
        REFERENCES klient(id_klient)
        ON DELETE CASCADE,
    CONSTRAINT fk_plac_transakcja
        FOREIGN KEY (id_plac)
        REFERENCES plac(id_plac)
        ON DELETE CASCADE,
    CONSTRAINT fk_sprzedawca_transakcja
        FOREIGN KEY (id_sprzedawca)
        REFERENCES sprzedawca(id_sprzedawca)
        ON DELETE CASCADE,
    CONSTRAINT fk_faktura_transakcja
        FOREIGN KEY (id_faktura)
        REFERENCES faktura(id_faktura)
        ON DELETE CASCADE
);

--------------------------------------------------------------------------------
CREATE TABLE historia_cen
(
    id_historia   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_samochod   NUMBER NOT NULL,
    stara_cena    NUMBER(20,2),
    nowa_cena     NUMBER(20,2),
    data_zmiany   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_samochod_historia
        FOREIGN KEY (id_samochod)
        REFERENCES samochod(id_samochod)
        ON DELETE CASCADE
);

--------------------------------------------------------------------------------
CREATE TABLE ubezpieczenie
(
    id_ubezpieczenie      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_samochod           NUMBER NOT NULL,
    firma_ubezpieczeniowa VARCHAR2(50) NOT NULL,
    nr_polisy             VARCHAR2(30) NOT NULL,
    data_poczatku         DATE NOT NULL,
    data_konca            DATE NOT NULL,
    koszt                 NUMBER(10,2),
    CONSTRAINT uq_ubezpieczenie_polis UNIQUE (nr_polisy),
    CONSTRAINT fk_samochod_ubezpieczenie
        FOREIGN KEY (id_samochod)
        REFERENCES samochod(id_samochod)
        ON DELETE CASCADE
);

--------------------------------------------------------------------------------
-- Indeksy (FK indeksy poprawiają wydajność joinów i delete cascade)
CREATE INDEX ix_plac_id_komis            ON plac(id_komis);
CREATE INDEX ix_dostawa_id_plac          ON dostawa(id_plac);
CREATE INDEX ix_dostawa_id_samochod      ON dostawa(id_samochod);
CREATE INDEX ix_sprzedawca_id_komis      ON sprzedawca(id_komis);
CREATE INDEX ix_sprzedawca_id_plac       ON sprzedawca(id_plac);
CREATE INDEX ix_trans_id_samochod        ON kartoteka_transakcji(id_samochod);
CREATE INDEX ix_trans_id_klient          ON kartoteka_transakcji(id_klient);
CREATE INDEX ix_trans_id_sprzedawca      ON kartoteka_transakcji(id_sprzedawca);
CREATE INDEX ix_trans_id_plac            ON kartoteka_transakcji(id_plac);
CREATE INDEX ix_trans_id_faktura         ON kartoteka_transakcji(id_faktura);
CREATE INDEX ix_historia_id_samochod     ON historia_cen(id_samochod);
CREATE INDEX ix_ubezpieczenie_id_samochod ON ubezpieczenie(id_samochod);
